apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # Workload Identity annotation connecting KSA to GSA
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}@{{ .Values.global.projectID }}.iam.gserviceaccount.com
