apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: {{ .Release.Namespace }}
  labels:
    app: result
spec:
  type: {{ .Values.result.service.type }}
  ports:
    - name: result-port
      port: {{ .Values.result.service.port }}
      targetPort: {{ .Values.result.service.targetPort }}
  selector:
    app: result
