apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: h0x3ein/rvote:2e16ed1
        envFrom:
          - configMapRef:
              name: voteapp-config
          - secretRef:
              name: voteapp-secret
        resources:
          requests:
            cpu: "100m"        
            memory: "64Mi"   
          limits:
            cpu: "200m"       
            memory: "128Mi" 
        livenessProbe:
          httpGet:
            path: /health    
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health    
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
