apiVersion: v1
kind: Pod
metadata:
  name: redis-tester
  labels:
    app: redis-tester
spec:
  containers:
  - name: redis-cli
    image: redis:latest
    # Keep the container running
    command: ["sleep", "3600"]
