name: run CI for voting app.

on:
    pull_request: 
    push: 
      branches:
      - main
      - feat/add-ci-cd
    workflow_dispatch: 

jobs:

  vote:
      env:
        IAMGE_NAME: rvote
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v5.0.0

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3.6.0
        
        - name:  Set up Docker Buildx
          uses:  docker/setup-buildx-action@v3.11.1
        
        - name: Login to Docker Registry
          uses: docker/login-action@v3.6.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN  }}
      
        - name: Get the tag name
          id: get_version
          run: echo "VERSION=git-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

        - name: Build and push Docker images
          uses: docker/build-push-action@v6.18.0
          with:
            context: ./vote
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IAMGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IAMGE_NAME }}:latest

  worker:
    env:
      IAMGE_NAME: rworker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      
      - name:  Set up Docker Buildx
        uses:  docker/setup-buildx-action@v3.11.1
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
    
      - name: Get the tag name
        id: get_version
        run: echo "VERSION=git-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./worker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IAMGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IAMGE_NAME }}:latest
    
  result:
    env:
      IAMGE_NAME: rresult
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      
      - name:  Set up Docker Buildx
        uses:  docker/setup-buildx-action@v3.11.1
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
    
      - name: Get the tag name
        id: get_version
        run: echo "VERSION=git-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./result
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IAMGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IAMGE_NAME }}:latest