name: run CI for voting app.

on:
    pull_request: 
    push: 
      branches:
      - main
      - feat/add-ci-cd
    workflow_dispatch: 

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  voting-app:
    strategy:
      fail-fast: false
      matrix:
        include:
        - service: vote
          image: rvote
          context: ./vote
        - service: worker
          image: rworker
          context: ./worker
        - service: result
          image: rresult
          context: ./result
    env:
      IMAGE_NAME: ${{ matrix.image }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      
      - name:  Set up Docker Buildx
        uses:  docker/setup-buildx-action@v3.11.1
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
    
      - name: Get the tag name
        id: get_version
        run: echo "VERSION=git-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and push ${{ matrix.service }} Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
