
on:
  workflow_call: 
    inputs:
      service:
        required: true
        type: string
      image:
        required: true
        type: string
      context:
        required: true
        type: string
      
      
jobs:
  voting-app:
    env:
      IMAGE_NAME: ${{ inputs.image }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      
      - name:  Set up Docker Buildx
        uses:  docker/setup-buildx-action@v3.11.1
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
    
      - name: Get the tag name
        id: get_version
        run: echo "VERSION=git-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build and push ${{ inputs.service }} Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ inputs.context }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
